### PR TITLE
Build this package on Travis

### PR DESCRIPTION
**Pull request by szepeviktor**
Using travis.debian.net

@jvrsantacruz Please turn on Travis.
Thanks.

### CODE REVIEW

**Comment by szepeviktor** [comment]
It is green: https://travis-ci.org/szepeviktor/dh-make-php/builds/187319603

**Comment by jvrsantacruz** [comment]
I'm requesting access so I can configure the project with Travis. 

Thanks for your work.

**Comment by szepeviktor** [comment]
@jvrsantacruz Any progress on Travis?

**Comment by szepeviktor** [comment]
@jvrsantacruz Any progress on enabling Travis?

**Comment by jvrsantacruz** [comment]
I'm really sorry this took us over a year to handle it. We'll strive to enable the Travis.
Thanks for your work and patience.

**Comment by szepeviktor** [comment]
@jvrsantacruz Any news on Travis?

**Comment by jvrsantacruz** [comment]
It should be enabled now https://travis-ci.org/Avature/dh-make-php
Would you mind taking a look to see if there is something else to do?

**Comment by szepeviktor** [comment]
I think Travis will run on the next PR or commit.

**Comment by szepeviktor** [comment]
Yes, it ran OK: https://travis-ci.org/Avature/dh-make-php/builds/346757328#L1731 in #19

**Pull request merged**
